### ISSUE TITLE
how to use i18nRouter outside the app.module.ts

### ISSUE THREAD

**Issue by ysus** [fulls1z3/ngx-i18n-router#11]
thnks for you repo is very usefull.
but i have a question:  i have two module the app.module and the fw.module , the fw.module is imported inside the app.module. the problem is that when i try to access to i18nRouter  with a component inside of fw.module
```
  <a [routerLink]="[''] | i18nRouter">
        ruta
    </a>
```
```
  i have the following error:

The pipe 'i18nRouter' could not be found 
    <a [ERROR ->][routerLink]="[''] | i18nRouter">
        <img class="small-image" src="{{menuService.endPoint}}/asse"): ng:///FwModule/TitleBarComponent.html@4:7
    at Error (native)
```

**Comment by fulls1z3** [comment]
hi @ysus, this repo has been severely affected by the breaking changes on both `@angular/router` and `@angular/compiler-cli` and needs some maintenance. I'll announce soon, with proper instructions.
